// <auto-generated />
using AcademyApp.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AcademyApp.Migrations
{
    [DbContext(typeof(AcademyDbContext))]
    [Migration("20190714133029_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AcademyApp.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EstimatedTime");

                    b.Property<int>("StudentId");

                    b.Property<int>("TimeSpent");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Projects");

                    b.HasData(
                        new { Id = 1, EstimatedTime = 10, StudentId = 1, TimeSpent = 20, Title = "Project_01" },
                        new { Id = 2, EstimatedTime = 8, StudentId = 1, TimeSpent = 4, Title = "Project_02" },
                        new { Id = 3, EstimatedTime = 4, StudentId = 1, TimeSpent = 3, Title = "Project_03" },
                        new { Id = 4, EstimatedTime = 4, StudentId = 2, TimeSpent = 3, Title = "Project_04" },
                        new { Id = 5, EstimatedTime = 7, StudentId = 2, TimeSpent = 3, Title = "Project_05" },
                        new { Id = 6, EstimatedTime = 54, StudentId = 2, TimeSpent = 12, Title = "Project_06" }
                    );
                });

            modelBuilder.Entity("AcademyApp.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Academy");

                    b.Property<int>("Age");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new { Id = 1, Academy = 1, Age = 35, FirstName = "Andrea", LastName = "Markovski" },
                        new { Id = 2, Academy = 3, Age = 22, FirstName = "Martin", LastName = "Vitanov" }
                    );
                });

            modelBuilder.Entity("AcademyApp.Models.Project", b =>
                {
                    b.HasOne("AcademyApp.Models.Student", "Student")
                        .WithMany("Projects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
